#!/usr/bin/env bash
# Copy this file to config/config.sh and edit the placeholder paths for your
# local system. The scripts source this file from the repository root.

export PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

# Shared execution settings
export CONDA_SH="${CONDA_SH:-$HOME/miniconda3/etc/profile.d/conda.sh}"
export METAWRAP_CONDA_ENV="${METAWRAP_CONDA_ENV:-metawrap}"
export CHECKM_CONDA_ENV="${CHECKM_CONDA_ENV:-}"
export DREP_CONDA_ENV="${DREP_CONDA_ENV:-drep}"
export QUAST_CONDA_ENV="${QUAST_CONDA_ENV:-}"
export GTDB_CONDA_ENV="${GTDB_CONDA_ENV:-}"
export MASH_CONDA_ENV="${MASH_CONDA_ENV:-mash}"
export MLST_CONDA_ENV="${MLST_CONDA_ENV:-}"
export KLETY_CONDA_ENV="${KLETY_CONDA_ENV:-dty}"
export PROKKA_CONDA_ENV="${PROKKA_CONDA_ENV:-prokka_env}"
export PANAROO_CONDA_ENV="${PANAROO_CONDA_ENV:-panaroo}"
export ABRICATE_CONDA_ENV="${ABRICATE_CONDA_ENV:-abricate}"
export PLATON_CONDA_ENV="${PLATON_CONDA_ENV:-platon}"
export MGEFINDER_CONDA_ENV="${MGEFINDER_CONDA_ENV:-mgefinder}"
export SPADES_CONDA_ENV="${SPADES_CONDA_ENV:-spades}"
export RNASEQ_CONDA_ENV="${RNASEQ_CONDA_ENV:-}"
export THREADS_DEFAULT="${THREADS_DEFAULT:-8}"
export THREADS_HIGH="${THREADS_HIGH:-24}"
export MIN_CONTIG_LENGTH="${MIN_CONTIG_LENGTH:-1000}"
export RUN_DREP="${RUN_DREP:-false}"

# Inputs
export SAMPLES_TSV="${SAMPLES_TSV:-$PROJECT_ROOT/config/samples.tsv}"
export RNASEQ_SAMPLES_TSV="${RNASEQ_SAMPLES_TSV:-$PROJECT_ROOT/config/rnaseq_samples.tsv}"
export RAW_READS_DIR="${RAW_READS_DIR:-$PROJECT_ROOT/data/raw_reads}"
export ASSEMBLY_INPUT_R1="${ASSEMBLY_INPUT_R1:-$PROJECT_ROOT/data/raw_reads/sample_R1.fastq.gz}"
export ASSEMBLY_INPUT_R2="${ASSEMBLY_INPUT_R2:-$PROJECT_ROOT/data/raw_reads/sample_R2.fastq.gz}"
export ASSEMBLY_GENOME_DIR="${ASSEMBLY_GENOME_DIR:-$PROJECT_ROOT/data/genomes}"
export ANNOTATION_INPUT_DIR="${ANNOTATION_INPUT_DIR:-$PROJECT_ROOT/data/genomes}"
export PANAROO_GFF_DIR="${PANAROO_GFF_DIR:-$PROJECT_ROOT/results/03_annotation/prokka_gff}"
export MAFFT_INPUT_FASTA="${MAFFT_INPUT_FASTA:-$PROJECT_ROOT/data/core_gene_alignment.fasta}"
export GTDB_INPUT_DIR="${GTDB_INPUT_DIR:-$PROJECT_ROOT/data/genomes}"
export MASH_QUERY_SIG_DIR="${MASH_QUERY_SIG_DIR:-$PROJECT_ROOT/data/mash/query_sig}"
export MASH_REFERENCE_SIG="${MASH_REFERENCE_SIG:-$PROJECT_ROOT/data/mash/reference/ref.sig}"
export KLETY_QUERY_LIST="${KLETY_QUERY_LIST:-$PROJECT_ROOT/data/klety/W_sm.txt}"
export KLETY_WORKDIR="${KLETY_WORKDIR:-$PROJECT_ROOT/data/klety}"
export KLETY_SCRIPT="${KLETY_SCRIPT:-$PROJECT_ROOT/tools/KleTy/KleTy.py}"
export ABRICATE_NCBI_INPUT_DIR="${ABRICATE_NCBI_INPUT_DIR:-$PROJECT_ROOT/data/genomes}"
export ABRICATE_CARD_INPUT_DIR="${ABRICATE_CARD_INPUT_DIR:-$PROJECT_ROOT/data/plasmids}"
export ABRICATE_VFDB_INPUT_DIR="${ABRICATE_VFDB_INPUT_DIR:-$PROJECT_ROOT/data/plasmids}"
export PLATON_INPUT_DIR="${PLATON_INPUT_DIR:-$PROJECT_ROOT/data/plasmids}"
export MGEFINDER_WORKDIR="${MGEFINDER_WORKDIR:-$PROJECT_ROOT/data/mgefinder}"
export SPADES_PLASMID_INPUT_DIR="${SPADES_PLASMID_INPUT_DIR:-$PROJECT_ROOT/data/plasmid_reads}"
export MUMMER_REFERENCE="${MUMMER_REFERENCE:-$PROJECT_ROOT/data/reference/reference.fna}"
export MUMMER_QUERY_DIR="${MUMMER_QUERY_DIR:-$PROJECT_ROOT/data/genomes}"
export LARGE_DEL_REFERENCE_FASTA="${LARGE_DEL_REFERENCE_FASTA:-$PROJECT_ROOT/data/reference/reference.fna}"
export LARGE_DEL_QUERY_DIR="${LARGE_DEL_QUERY_DIR:-$PROJECT_ROOT/data/large_deletion/query}"
export LARGE_DEL_ALIGNMENT_INPUT_DIR="${LARGE_DEL_ALIGNMENT_INPUT_DIR:-$PROJECT_ROOT/data/large_deletion/alignment}"
export LARGE_DEL_MARKDUP_DIR="${LARGE_DEL_MARKDUP_DIR:-$PROJECT_ROOT/data/large_deletion/alignment}"
export RNASEQ_RAW_DIR="${RNASEQ_RAW_DIR:-$PROJECT_ROOT/data/rnaseq/raw}"
export RNASEQ_GTF="${RNASEQ_GTF:-$PROJECT_ROOT/data/annotation/genes.gtf}"
export HISAT2_INDEX_PREFIX="${HISAT2_INDEX_PREFIX:-$PROJECT_ROOT/data/rnaseq/index/genome}"
export LARGE_DEL_REGIONS_LIST="${LARGE_DEL_REGIONS_LIST:-$PROJECT_ROOT/data/large_deletion/regions.list}"
export WHAM_FILTER_SCRIPT="${WHAM_FILTER_SCRIPT:-$PROJECT_ROOT/tools/wham/utils/filtWhamG.pl}"

# Outputs
export ASSEMBLY_OUTPUT_DIR="${ASSEMBLY_OUTPUT_DIR:-$PROJECT_ROOT/results/01_assembly_qc/metawrap}"
export FILTERED_CONTIGS_DIR="${FILTERED_CONTIGS_DIR:-$PROJECT_ROOT/results/01_assembly_qc/filtered_contigs}"
export QUAST_OUTPUT_DIR="${QUAST_OUTPUT_DIR:-$PROJECT_ROOT/results/01_assembly_qc/quast}"
export CHECKM_OUTPUT_DIR="${CHECKM_OUTPUT_DIR:-$PROJECT_ROOT/results/01_assembly_qc/checkm}"
export DREP_OUTPUT_DIR="${DREP_OUTPUT_DIR:-$PROJECT_ROOT/results/01_assembly_qc/drep}"
export GTDB_OUTPUT_DIR="${GTDB_OUTPUT_DIR:-$PROJECT_ROOT/results/02_species_typing/gtdb}"
export MASH_OUTPUT_DIR="${MASH_OUTPUT_DIR:-$PROJECT_ROOT/results/02_species_typing/mash}"
export MLST_OUTPUT_DIR="${MLST_OUTPUT_DIR:-$PROJECT_ROOT/results/02_species_typing/mlst}"
export KLETY_OUTPUT_DIR="${KLETY_OUTPUT_DIR:-$PROJECT_ROOT/results/02_species_typing/klety}"
export PROKKA_OUTPUT_DIR="${PROKKA_OUTPUT_DIR:-$PROJECT_ROOT/results/03_annotation/prokka}"
export MAFFT_OUTPUT_FILE="${MAFFT_OUTPUT_FILE:-$PROJECT_ROOT/results/04_phylogeny_pangenome/mafft/alignment.fasta}"
export PANAROO_OUTPUT_DIR="${PANAROO_OUTPUT_DIR:-$PROJECT_ROOT/results/04_phylogeny_pangenome/panaroo}"
export ABRICATE_NCBI_OUTPUT_DIR="${ABRICATE_NCBI_OUTPUT_DIR:-$PROJECT_ROOT/results/05_amr_virulence/abricate/ncbi}"
export ABRICATE_CARD_OUTPUT_DIR="${ABRICATE_CARD_OUTPUT_DIR:-$PROJECT_ROOT/results/05_amr_virulence/abricate/card}"
export ABRICATE_VFDB_OUTPUT_DIR="${ABRICATE_VFDB_OUTPUT_DIR:-$PROJECT_ROOT/results/05_amr_virulence/abricate/vfdb}"
export ABRICATE_MERGED_OUTPUT="${ABRICATE_MERGED_OUTPUT:-$PROJECT_ROOT/results/05_amr_virulence/merged/abricate_merged.tsv}"
export VFDB_MERGED_OUTPUT="${VFDB_MERGED_OUTPUT:-$PROJECT_ROOT/results/05_amr_virulence/merged/vfdb_merged.tsv}"
export PLATON_OUTPUT_DIR="${PLATON_OUTPUT_DIR:-$PROJECT_ROOT/results/06_plasmid_mge/platon}"
export MGEFINDER_OUTPUT_DIR="${MGEFINDER_OUTPUT_DIR:-$PROJECT_ROOT/results/06_plasmid_mge/mgefinder}"
export SPADES_PLASMID_OUTPUT_DIR="${SPADES_PLASMID_OUTPUT_DIR:-$PROJECT_ROOT/results/06_plasmid_mge/spades_plasmid}"
export MUMMER_OUTPUT_DIR="${MUMMER_OUTPUT_DIR:-$PROJECT_ROOT/results/07_large_deletion/mummer}"
export LARGE_DEL_OUTPUT_DIR="${LARGE_DEL_OUTPUT_DIR:-$PROJECT_ROOT/results/07_large_deletion/wham}"
export RNASEQ_TRIM_DIR="${RNASEQ_TRIM_DIR:-$PROJECT_ROOT/results/08_rnaseq/trimmed}"
export RNASEQ_ALIGN_DIR="${RNASEQ_ALIGN_DIR:-$PROJECT_ROOT/results/08_rnaseq/hisat2}"
export RNASEQ_COUNTS_DIR="${RNASEQ_COUNTS_DIR:-$PROJECT_ROOT/results/08_rnaseq/counts}"
export RNASEQ_DESEQ2_DIR="${RNASEQ_DESEQ2_DIR:-$PROJECT_ROOT/results/08_rnaseq/deseq2}"
export FIGURE_OUTPUT_DIR="${FIGURE_OUTPUT_DIR:-$PROJECT_ROOT/results/09_figures}"
export QC_SUMMARY_TSV="${QC_SUMMARY_TSV:-$PROJECT_ROOT/results/01_assembly_qc/qc_summary.tsv}"
export AMR_SUMMARY_TSV="${AMR_SUMMARY_TSV:-$ABRICATE_MERGED_OUTPUT}"
export LARGE_DEL_SUMMARY_TSV="${LARGE_DEL_SUMMARY_TSV:-$PROJECT_ROOT/results/07_large_deletion/large_deletions.tsv}"
export RNASEQ_RESULTS_TSV="${RNASEQ_RESULTS_TSV:-$RNASEQ_DESEQ2_DIR/deseq2_results.tsv}"

# Software and database placeholders.
export GTDBTK_DATA_PATH="${GTDBTK_DATA_PATH:-/path/to/gtdbtk/data}"
export CHECKM_DATA_PATH="${CHECKM_DATA_PATH:-/path/to/checkm/data}"
export PLATON_DB="${PLATON_DB:-/path/to/platon/db}"
export ABRICATE_DB_NCBI="${ABRICATE_DB_NCBI:-ncbi}"
export ABRICATE_DB_CARD="${ABRICATE_DB_CARD:-card}"
export ABRICATE_DB_VFDB="${ABRICATE_DB_VFDB:-vfdb}"
export MUMMER_THREADS="${MUMMER_THREADS:-24}"
export RNASEQ_THREADS="${RNASEQ_THREADS:-8}"
